### ISSUE TITLE
Missing image for CSI_PROVISIONER_IMAGE and PROVISIONER_IMAGE

### ISSUE THREAD

**Issue by tommymalmqvist** [kubevirt/hostpath-provisioner-operator#128]
`CSI_PROVISIONER_IMAGE` and `PROVISIONER_IMAGE` currently points to `registry:5000`.

I did find `PROVISIONER_IMAGE` available at `quay.io/kubevirt/hostpath-provisioner:latest`

```
1889             - name: PROVISIONER_IMAGE
1890               value: "registry:5000/hostpath-provisioner:latest"
1891             - name: CSI_PROVISIONER_IMAGE
1892               value: "registry:5000/hostpath-provisioner-csi:latest"

```

**Comment by awels** [comment]
Oops, sorry let me fix the deployment, I am in the middle of a rewrite to make the hostpath provisioner a csi driver.

**Comment by awels** [comment]
If you want the old style deployment, I suggest you grab the artifacts from https://github.com/kubevirt/hostpath-provisioner-operator/releases/tag/v0.9.0 those should all work fine.

**Comment by tommymalmqvist** [comment]
Ok, thanks @awels

**Comment by awels** [comment]
Okay fixed, main will work with the old style provisioner (I have not released csi container yet). Make sure to use the disableCsi: true in your cr.

**Comment by awels** [comment]
Closing, if you need to re-open feel free to do so.
