### ISSUE TITLE
hostpath-provisioner-operator fails to install on Single Node OpenShift

### ISSUE THREAD

**Issue by sanjeevshar** [kubevirt/hostpath-provisioner-operator#186]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
hostpath-provisioner-operator pod fails to come up on Single Node OpenShift installation.

[core@opti-7090 hostpath]$ oc get po -n hostpath-provisioner
NAME                                             READY   STATUS              RESTARTS   AGE
hostpath-provisioner-operator-77c9dbf667-2bgq6   0/1     ContainerCreating   0          59m

Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    58m                   default-scheduler  Successfully assigned hostpath-provisioner/hostpath-provisioner-operator-77c9dbf667-2bgq6 to opti-7090
  Warning  FailedMount  40m (x2 over 54m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[apiservice-cert], unattached volumes=[kube-api-access-7qvt5 apiservice-cert]: timed out waiting for the condition
  Warning  FailedMount  13m (x17 over 56m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[apiservice-cert], unattached volumes=[apiservice-cert kube-api-access-7qvt5]: timed out waiting for the condition
  Warning  FailedMount  3m39s (x35 over 58m)  kubelet            MountVolume.SetUp failed for volume "apiservice-cert" : secret "hostpath-provisioner-operator-webhook-service-cert" not found

**What you expected to happen**:
Successful operator installation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Single Node OpenShift (SNO) using assisted installer as described at:
https://docs.openshift.com/container-platform/4.9/installing/installing_sno/install-sno-installing-sno.html
2. Install hostpath-provisioner-operator 

**Anything else we need to know?**
OpenShift version: 4.8.17
**Environment**:
- Kubernetes version (use `kubectl version`): v1.21

- Cloud provider or hardware configuration: Intel X86 PC with 16 core cpu and 32 Gig memory
- Install tools:
- Others:
[hostpath_pod_status.txt](https://github.com/kubevirt/hostpath-provisioner-operator/files/7715042/hostpath_pod_status.txt)

**Comment by awels** [comment]
So the error you are seeing is that the certificate request is not being fulfilled. However I suspect if you add these two yamls, the Open Shift cert manager will take care of creating the right certificates
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: kubevirt-hyperconverged
  name: hostpath-provisioner-operator-webhook-service-cert
  labels:
    name: hostpath-provisioner-operator
spec:
  secretName: hostpath-provisioner-operator-webhook-service-cert
  dnsNames:
  - hostpath-provisioner-operator-webhook-service.hostpath-provisioner.svc
  issuerRef:
    name: selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: hostpathprovisioner.kubevirt.io
  annotations:
    cert-manager.io/inject-ca-from: hostpath-provisioner/hostpath-provisioner-operator-webhook-service-cert
  labels:
    name: hostpath-provisioner-operator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: hostpath-provisioner-operator-webhook-service
      namespace: hostpath-provisioner
      path: /validate-hostpathprovisioner-kubevirt-io-v1beta1-hostpathprovisioner
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-hostpath-provisioner.kubevirt.io
  objectSelector: {}
  rules:
  - apiGroups:
    - hostpathprovisioner.kubevirt.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - "*/*"
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```

**Comment by sanjeevshar** [comment]
I installed cert manager operator and added self singed issuer on OpenShift as well added the Yaml that you provided but the problem still exists.  Am I missing anything?

**Comment by awels** [comment]
Can you verify that the certificates have been properly created? There should be a secret called `hostpath-provisioner-operator-webhook-service-cert` in the hostpath provisioner namespace.

**Comment by sanjeevshar** [comment]
I see one in kubevirt-hyperconverged namespace but not in hostpath-provisioner. 

[core@cluster2 hostpath]$ kubectl get secret  -n hostpath-provisioner
NAME                                            TYPE                                  DATA   AGE
builder-dockercfg-l56nn                         kubernetes.io/dockercfg               1      107m
builder-token-cvqq9                             kubernetes.io/service-account-token   4      107m
builder-token-wcn8w                             kubernetes.io/service-account-token   4      107m
default-dockercfg-zc6fp                         kubernetes.io/dockercfg               1      107m
default-token-hpnf5                             kubernetes.io/service-account-token   4      107m
default-token-slrgv                             kubernetes.io/service-account-token   4      107m
deployer-dockercfg-97f89                        kubernetes.io/dockercfg               1      107m
deployer-token-7z9m9                            kubernetes.io/service-account-token   4      107m
deployer-token-fcvlw                            kubernetes.io/service-account-token   4      107m
hostpath-provisioner-operator-dockercfg-jxngg   kubernetes.io/dockercfg               1      106m
hostpath-provisioner-operator-token-krzm6       kubernetes.io/service-account-token   4      106m
hostpath-provisioner-operator-token-mz79c       kubernetes.io/service-account-token   4      106m

[core@cluster2 hostpath]$ kubectl get secret  -n kubevirt-hyperconverged
NAME                                                       TYPE                                  DATA   AGE
builder-dockercfg-rqltb                                    kubernetes.io/dockercfg               1      143m
builder-token-dtrgj                                        kubernetes.io/service-account-token   4      143m
builder-token-ht6hm                                        kubernetes.io/service-account-token   4      143m
default-dockercfg-vn7n4                                    kubernetes.io/dockercfg               1      143m
default-token-bl7dg                                        kubernetes.io/service-account-token   4      143m
default-token-hqwbd                                        kubernetes.io/service-account-token   4      143m
deployer-dockercfg-hh8jd                                   kubernetes.io/dockercfg               1      143m
deployer-token-g6bq2                                       kubernetes.io/service-account-token   4      143m
deployer-token-tdf48                                       kubernetes.io/service-account-token   4      143m
hostpath-provisioner-operator-webhook-service-cert-h8dzm   Opaque                                1      86m

**Comment by awels** [comment]
oh you have the HCO installed as well? That comes with hpp already, so you don't need to install it again. It is likely conflicting.

**Comment by sanjeevshar** [comment]
This is so confusing. I installed OpenShift Virtualization because I need to deploy VMs. I did not know that HPP is inbuilt. So just use what you see in the attached screenshot.
![image](https://user-images.githubusercontent.com/26364027/146239400-3cf3a42b-4da2-4202-987f-70a12d2a69c9.png)

**Comment by awels** [comment]
Okay, yes just click create instance for the hostpath provisioner and accept the values that are populated. This will install 0.9 of the hostpath provisioner btw. 4.10 will include 0.11

**Comment by sanjeevshar** [comment]
I reinstalled cluster and created instance of HPP but did  not see option of storagePools so I created 'legacy' storage class but PVC was always in pending state when I created a pod.
![image](https://user-images.githubusercontent.com/26364027/146269691-f04d30bb-d9fc-4b98-a5ca-722525340d9d.png)

**Comment by awels** [comment]
Yes that is correct, 4.9 only has the legacy version of hpp, in 4.10 it will be a CSI driver. I suspect you need to create a MachineConfig that creates the directory and sets the proper selinux labels. We have an example here https://github.com/kubevirt/hostpath-provisioner-operator/blob/main/contrib/machineconfig-selinux-hpp.yaml, for SNO you only need one

**Comment by sanjeevshar** [comment]
Still no luck. No PV gets created. 
generated from persistentvolume-controller
42 times in the last 10 minutes
waiting for a volume to be created, either by external provisioner "kubevirt.io.hostpath-provisioner" or manually created by system administrato

**Comment by awels** [comment]
I am assuming you created a storage class? If not you should create one like this one: https://github.com/kubevirt/hostpath-provisioner-operator/blob/main/deploy/storageclass-wffc.yaml and you will notice the `volumeBindingMode: WaitForFirstConsumer` which means you need a consumer (pod/VM) before the PV is provisioned. If that is still not happening afterwards, look in openshift-cnv namespace in the hostpath-provisioner-xxxxx-yyy pod logs to see what is going on.

**Comment by sanjeevshar** [comment]
I have created the storage class and made it default SC. No Pod deployment is not successful using the created PVC.
[core@cluster2 ~]$ oc describe sc hostpath-csi
Name:                  hostpath-csi
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           kubevirt.io.hostpath-provisioner
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>

provisioner logs:
I1216 18:28:38.031704       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:28:38.031723       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:28:38.031728       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:28:38.031741       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:28:38.031749       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:28:38.031752       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
E1216 18:29:21.044875       1 reflector.go:383] /remote-source/app/controller/controller.go:809: Failed to watch *v1.StorageClass: Get "https://172.30.0.1:443/apis/storage.k8s.io/v1/storageclasses?allowWatchBookmarks=true&resourceVersion=1482506&timeout=8m24s&timeoutSeconds=504&watch=true": dial tcp 172.30.0.1:443: connect: connection refused
E1216 18:29:21.045236       1 reflector.go:383] /remote-source/app/controller/controller.go:803: Failed to watch *v1.PersistentVolumeClaim: Get "https://172.30.0.1:443/api/v1/persistentvolumeclaims?allowWatchBookmarks=true&resourceVersion=1483056&timeout=6m12s&timeoutSeconds=372&watch=true": dial tcp 172.30.0.1:443: connect: connection refused
E1216 18:29:21.045450       1 reflector.go:383] /remote-source/app/controller/controller.go:806: Failed to watch *v1.PersistentVolume: Get "https://172.30.0.1:443/api/v1/persistentvolumes?allowWatchBookmarks=true&resourceVersion=1482791&timeout=6m33s&timeoutSeconds=393&watch=true": dial tcp 172.30.0.1:443: connect: connection refused
I1216 18:29:26.856419       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:29:26.869896       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:29:26.902713       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:29:26.869844       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:29:26.941692       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:29:26.952697       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:44:26.856505       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:44:26.856521       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:44:26.856543       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:44:26.856557       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:44:26.856564       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:44:26.856586       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:59:26.856599       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:59:26.856615       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:59:26.856620       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 18:59:26.856676       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 18:59:26.856684       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 18:59:26.856687       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 19:13:56.959390       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:13:56.959524       1 hostpath-provisioner.go:118] missing volume.kubernetes.io/selected-node annotation, skipping operations for pvc
I1216 19:14:01.286033       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:14:01.286049       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 19:14:01.286052       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 19:14:01.289539       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:14:01.289557       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 19:14:01.289562       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 19:14:26.856783       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:14:26.856802       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 19:14:26.856806       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 19:14:26.856828       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:14:26.856836       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 19:14:26.856838       1 hostpath-provisioner.go:95] isCorrectNodeByBindingMode mode: WaitForFirstConsumer
I1216 19:14:26.856842       1 hostpath-provisioner.go:110] claim included volume.kubernetes.io/selected-node annotation: cluster2
I1216 19:14:26.856839       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2
I1216 19:14:26.856844       1 hostpath-provisioner.go:112] matched volume.kubernetes.io/selected-node: cluster2 with this node: cluster2

**Comment by awels** [comment]
You created the wrong storage class, since you are using SNO 4.9, it is using the 'legacy' provisioner, and you need to use the legacy storage class like I showed above
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-provisioner
provisioner: kubevirt.io/hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Notice the `/` in the provisioner vs the `.` in the one you have.

**Comment by sanjeevshar** [comment]
That worked. Thank you !!!

Please note that I had created SC with file: deploy/storageclass-wffc-legacy-csi.yaml 
If it is not for legacy, then filename is misleading.  The legacy provisioner is in file storageclass-wffc.yaml.

**Comment by awels** [comment]
Right, so in version 0.10 and above of the hpp operator, it supports an upgrade path from the 0.9 legacy to the new CSI driver. And that is what the storageclass-wffc-legacy-csi.yaml is for. I should probably rename storageclass-wffc.yaml to storageclass-wffc-legacy.yaml

Note for SNO 4.10, it will support hpp 0.11 or newer, and you don't need the MachineConfig or many of the things we talked about here. It will default to the CSI driver as well.

**Comment by sanjeevshar** [comment]
That would be great. Thank you for all your help to get me started. Looking forward to SNO 4.10 :)

**Comment by awels** [comment]
One thing to point out, you can change the path that is used to mount. If your cluster has a separate disk you would like to use, I highly suggest you modify the MachineConfig to mount that disk somewhere, and then point the HPP CR to that path. That way you don't run out of space on the OS partition and crash your node (yes it will because unusable once you get into disk pressure on the node).
