### ISSUE TITLE
Buildah insecure registry support

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/hostpath-provisioner-operator#253]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
While trying to  `make push` getting a bunch of errs `http: server gave HTTP response to HTTPS client`

**What you expected to happen**:
Something like https://github.com/kubevirt/hostpath-provisioner/blob/f24ea1fec164935c55e1345507970e806e7f8988/cluster-sync/sync.sh#L32 in here too maybe?

**How to reproduce it (as minimally and precisely as possible)**:
kubevirtci local registry, `make push` to it

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Solved by #263
