### ISSUE TITLE
Include csv-generator in container image

### ISSUE THREAD

**Issue by djzager** [kubevirt/hostpath-provisioner-operator#28]
To make integration with the HyperConverged Cluster Operator easier, we are working to use `csv-generator` for building all of the manifests (including the converged CSV). 

I attempted to update my [PR](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/333) to handle this operator but see that the `csv-generator` hasn't been added to the image yet.

```
Digest: sha256:b05394d2a9832c161d172254cc83d4d0760e165afd2e8c2d686173910e21071f
Status: Downloaded newer image for quay.io/kubevirt/hostpath-provisioner-operator:v0.2.3
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/csv-generator\": stat /usr/bin/csv-generator: no such file or directory": unknown.
```

**Comment by awels** [comment]
Right, I added the code for the csv-generator, but specifically didn't add it to the published container on quay.io. Its no problem to add, but haven't had a use case to actually add it to the published container.
