### ISSUE TITLE
contrib/export.sh fails with unknown flag error

### ISSUE THREAD

**Issue by dcritch** [kubevirt/hostpath-provisioner-operator#85]
When trying to export VMs from a OCP 3.11 using [export.sh](https://github.com/kubevirt/hostpath-provisioner-operator/blob/master/contrib/export.sh), the operation fails with an unknown flag error:
~~~
$ ./export.sh worker-2.example.com
Python 3 is installed, continuing
Checking node: worker-2.example.com
Found node worker-2.example.com
Creating output directory for node worker-2.example.com
Export failed, worker-2.example.com/export.json is corrupt
error executing ['kubectl', 'get', 'pv', 'pvc-67e56c42-09a5-11eb-affa-beeffeed0097', '--export', '-o', 'json', '--kubeconfig', '/home/davidc/rc/ocp/dc-ocp4/auth/kubeconfig']Error: unknown flag: --export
See 'kubectl get --help' for usage.
~~~

Seems like `--export` is no longer a support argument, however running the script without the option allows for a successful export/import.

**Comment by awels** [comment]
So looking at your arguments, you are using an ocp 4 kubeconfig, and I suspect an ocp 4 kubectl (kubectl --version will tell you). I know in some of the newest kubernetes that flag is obsolete, but OS 3.11 kubectl (or oc) should still have it. It strips out a bunch of the generated fields we don't care about.

**Comment by dcritch** [comment]
Yeah. When I ran it back when I was testing upgrades to 4.5 things were fine, but it might have been awhile since I updated the client.

But as a user, I figured I'm more likely to have an updated client when running the migration.

The stuff it strips out and we don't care about... is it a problem if its there? If not, then not using the flag even if using an older client probably isn't that bad either.

**Comment by awels** [comment]
My point is, if you are exporting from OS 3.11, you should be using the client that comes with OS 3.11, not the client that comes with OCP 4.x

**Comment by dcritch** [comment]
I agree, but that likely isn't a reality since we say the clients are generally backwards compatible and the customer would already have an updated client in their environment while testing 4.x.

**Comment by awels** [comment]
Okay, I am not that passionate one way or the other. The only difference is just some extra meta data that will be ignored anyway when importing.

**Comment by dcritch** [comment]
Thanks!
